Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.DAO;
using WetCat.Models;

namespace WetCat.Controllers
{
    public class AdminController: Controller
    {
        WetCat_DBContext DB = new WetCat_DBContext();

        PostDAO PostDAO = new PostDAO();
        public AdminController(){}

        public IActionResult Index(){
            if (HttpContext.Session.GetString("username") != "admin") {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }  
            var postLists = PostDAO.GetAllPosts().ToList();
            return View(postLists);
        }

        public ActionResult Delete(int postid){
            if (HttpContext.Session.GetString("username") != "admin") {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            } 
            if (postid == 0){
                return NotFound();
            }
            var post = PostDAO.FindPost(postid);
            if (post == null){
                return NotFound();
            }
            return View(post);
        }
        
        [HttpPost]
        public ActionResult Delete1(int postid){
            if (HttpContext.Session.GetString("username") != "admin") {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            } 
            try {
                PostDAO.EditPost1(PostDAO.FindPost(postid)); 
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex){
                ViewBag.Message = ex.Message;
            }
            return View();
        }

        public ActionResult ShowPost(int postid){
            if (HttpContext.Session.GetString("username") != "admin") {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            } 
            if (postid.Equals("")){
                return NotFound();
            }
            var post = PostDAO.GetPost(postid);
            if (post == null){
                return NotFound();
            }
            return View(post);
        }

        [HttpPost]
        public ActionResult ShowPost(Post post){
            if (HttpContext.Session.GetString("username") != "admin") {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            } 
            try {
                PostDAO.GetPosts();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex){
                ViewBag.Message = ex.Message;
            }
            return View();
        }
    }
}

Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.DAO;
using WetCat.Models;

namespace WetCat.Controllers
{
    public class UserManagementController: Controller
    {
        WetCat_DBContext DB = new WetCat_DBContext();

        UserDAO UserDAO = new UserDAO();
        public UserManagementController(){}

        public IActionResult Index(){
            if (HttpContext.Session.GetString("username") == null) {
                return RedirectToAction("Index", "Home");
            }  
            var users = UserDAO.GetUsers().ToList();
            System.Console.WriteLine(users.Count);
            return View(users);
        }
        
        public ActionResult Delete(string username){
            if (username == null){
                return NotFound();
            }
            var user = UserDAO.GetUserByUsername(username);
            if (user == null){
                return NotFound();
            }
            return View(user);
        }

        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(User user){
            try {
                using var _db = new WetCat_DBContext();
                _db.Users.Update(user);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex){
                ViewBag.Message = ex.Message;
            }
            return View();
        }
        */

        [HttpPost]
        public ActionResult Delete1(string username){
            try {
                UserDAO.EditUSer1(UserDAO.GetUserByUsername(username)); 
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex){
                ViewBag.Message = ex.Message;
            }
            return View();
        }

        public ActionResult ShowUser(string username){
            if (username == null){
                return NotFound();
            }
            var user = UserDAO.GetUserByUsername(username);
            if (user == null){
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        public ActionResult ShowUser(User user){
            try {
                UserDAO.GetUsers();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex){
                ViewBag.Message = ex.Message;
            }
            return View();
        }
    }
}

Views/UserManagement/Delete.cshtml
@model User
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure you want to delete this User?</h2>

<hr>
<form method="POST" asp-action="Delete1">
    <div class="row">
        <b class="col-6">Username</b>
        <div class="col-6">@Model.Username</div>
    </div>
    <div class="row">
        <b class="col-6">Email</b>
        <div class="col-6">@Model.UserMail</div>
    </div>
    <div class="row">
        <b class="col-6">Avatar</b>
        <div class="col-6">
            <img style="width:100px; height: 100px;" src="@Model.AvatarSrc" alt="">
        </div>
    </div>
    <div class="row">
        <b class="col-6">Nickname</b>
        <div class="col-6">@Model.Nickname</div>
    </div>
    <div class="row">
        <b class="col-6">Gender</b>
        <div class="col-6">@Model.Gender</div>
    </div>
    <div class="row">
        <b class="col-6">Phone</b>
        <div class="col-6">@Model.Phone</div>
    </div>
    <div class="row">
        <b class="col-6">Birthday</b>
        <div class="col-6">@Model.Birthday.ToShortDateString()</div>
    </div>
    <br> 
    <div>
        <input type="submit" value="Delete" class="btn btn-danger" asp-controller="UserManagement" asp-action="Delete1" asp-route-username="@Model.Username"/>

        @Html.ActionLink("<Back to list", "Index") 
    </div>
</form>

Views/UserManagement/Index.cshtml
@model IEnumerable<User>
@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>User Management Page</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/admin_bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/admin_style.css" rel="stylesheet">
</head>

<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a asp-action="Index" asp-controller="Admin" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>WETCAT</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="/images/profiles/admin/logo.jpg" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">Admin</h6>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a asp-action="Index" asp-controller="Admin" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Post Management</a>
            <a asp-action="Index" asp-controller="UserManagement" class="nav-item nav-link active"><i class="fa fa-th me-2"></i>User Management</a>
        </div>
    </nav>
</div>

<body>
    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
            <a asp-action="Index" asp-controller="Admin" class="navbar-brand d-flex d-lg-none me-4">
                <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
            </a>
            <a href="#" class="sidebar-toggler flex-shrink-0">
                <i class="fa fa-bars"></i>
            </a>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control border-0" type="search" placeholder="Search User">
            </form>
            <!--
            @using (Html.BeginForm("SearchUSer", "UserManagement"))
            {
                @Html.TextBox("Query")
                <input type="submit" value="search" />
            }
            -->

            <div class="navbar-nav align-items-center ms-auto">
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <img class="rounded-circle me-lg-2" src="/images/profiles/admin/logo.jpg" alt="" style="width: 40px; height: 40px;">
                        <span class="d-none d-lg-inline-flex">Admin</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a asp-action="Logout" asp-controller="Home" class="dropdown-item">Log out</a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Navbar End -->

        <!-- User List Start -->
        <div class="container-fluid pt-4 px-4">
            <div class="bg-light text-center rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <h4 class="mb-0">User List</h4>
                    <a href="">Refresh</a>
                </div>
                <div class="table-responsive">
                    <table class="table text-start align-middle table-bordered table-hover mb-0">
                        <thead>
                            <tr class="text-dark"> 
                                <th style="text-align: center;" scope="col">Username</th>
                                <th style="text-align: center;" scope="col">Email</th>
                                <th style="text-align: center;" scope="col">Avatar</th>
                                <th style="text-align: center;" scope="col">Nickname</th>
                                <th style="text-align: center;" scope="col">Gender</th>
                                <th style="text-align: center;" scope="col">Phone</th>
                                <th style="text-align: center;" scope="col">Birthday</th>
                                <th style="text-align: center; width: 100px;" scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                @foreach (var item in Model)
                                {
                                    if(item.IsDeleted != 1){
                                        <tr>
                                            <td style="text-align: center;  width: 70px;">@item.Username</td>
                                            <td>@item.UserMail</td>
                                            <td>
                                                <img style="width:100px; height: 100px;" src="@item.AvatarSrc" alt="">
                                            </td>
                                            <td>@item.Nickname</td>
                                            @{
                                                string gender = "";
                                                if(item.Gender==1)
                                                {
                                                    gender = "Male";
                                                }
                                                else if (item.Gender==0){
                                                    gender = "Female";
                                                }
                                            }
                                            <td style="text-align: center;">@gender</td>
                                            <td style="text-align: center;">@item.Phone</td>
                                            <td style="text-align: center;">@item.Birthday.ToShortDateString()</td>
                                            <td style="text-align: center;">
                                            <a class="fas fa-trash" asp-action = "Delete" asp-controller="UserManagement" asp-route-username="@item.Username"></a>
                                            <a class="fa fa-info-circle" asp-action = "ShowUser" asp-controller="UserManagement" asp-route-username="@item.Username"></a>
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- User List End -->

        <!-- Footer Start -->
        <div class="container-fluid pt-4 px-4">
            <div class="bg-light rounded-top p-4">
                <div class="row">
                    <div class="col-12 col-sm-6 text-center text-sm-start">
                        &copy;  <a asp-action="Index" asp-controller="Home">WetCat Social Networking Site</a>, All Right Reserved. 
                    </div>
                    <div class="col-12 col-sm-6 text-center text-sm-end">
                        Designed By <a href="Group2.txt">Group 2</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
    </div>
    <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/chart/chart.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/admin_main.js"></script>
</body>

</html>

Views/UserManagement/ShowUser.cshtml
@model User
@{
    ViewData["Title"] = "ShowUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr>
<form method="POST" asp-action="ShowUser">
    <div class="row">
        <b class="col-6">Username</b>
        <div class="col-6">@Model.Username</div>
    </div>
    <div class="row">
        <b class="col-6">Email</b>
        <div class="col-6">@Model.UserMail</div>
    </div>
    <div class="row">
        <b class="col-6">Avatar</b>
        <div class="col-6">
            <img style="width:100px; height: 100px;" src="@Model.AvatarSrc" alt="">
        </div>
    </div>
    <div class="row">
        <b class="col-6">Nickname</b>
        <div class="col-6">@Model.Nickname</div>
    </div>
    <div class="row">
        <b class="col-6">Gender</b>
        <div class="col-6">@Model.Gender</div>
    </div>
    <div class="row">
        <b class="col-6">Phone</b>
        <div class="col-6">@Model.Phone</div>
    </div>
    <div class="row">
        <b class="col-6">Birthday</b>
        <div class="col-6">@Model.Birthday.ToShortDateString()</div>
    </div>
    <br> 
    <div>
        @Html.ActionLink("<Back to list", "Index") 
    </div>
</form>