Models/Friend.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace WetCat.Models
{
    public partial class Friend
    {
        public string FirstUsername { get; set; }
        public string SecondUsername { get; set; }
        public int? FriendStatus { get; set; }
        public DateTime? StatusTime { get; set; }
        public int? IsDeleted { get; set; }

        public virtual User FirstUsernameNavigation { get; set; }
        public virtual User SecondUsernameNavigation { get; set; }
    }
}

Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.DAO;
using WetCat.Models;

namespace WetCat.Controllers {
    public class FriendController : Controller {
        FriendDAO friendDAO = new FriendDAO ();
        public FriendController () { }

        public IActionResult Index () {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            List<Friend> friendlist = friendDAO.GetFriendList (HttpContext.Session.GetString ("username"));
            return View (friendlist);
        }
        public IActionResult RequestList () {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            List<Friend> requestList = friendDAO.GetRequestList(HttpContext.Session.GetString ("username"));
            requestList = requestList.OrderBy(p => p.StatusTime).Reverse<Friend>().ToList();
            return View (requestList);
        }
        public IActionResult FriendStatus (string id) {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            System.Console.WriteLine ("ID KB: " + id);
            Friend fr = friendDAO.GetFrienders (HttpContext.Session.GetString ("username"), id);
            if (fr == null) {
                fr = new Friend();  
                fr.FirstUsername = "";
                fr.SecondUsername = id;
            }
            return PartialView ("/Views/Friend/_FriendStatus.cshtml", fr);
        }

        public IActionResult AddFriend (string usn) {
            try {
                if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
                friendDAO.AddFriend (HttpContext.Session.GetString("username"), usn);
                NotificationListController.sendNoti("request", null, null, HttpContext.Session.GetString("username"),usn);
            } catch (Exception e) {
                System.Console.WriteLine(e.InnerException.Message);
            }
            
            return Redirect ("/Wall/" + usn + "/timeline");
        }
        public IActionResult AcceptAtWall(string usn) {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            friendDAO.AcceptRequest(HttpContext.Session.GetString("username"), usn);
            NotificationListController.sendNoti("accept", null, null, HttpContext.Session.GetString("username"),usn);
            return Redirect ("/Wall/" + usn + "/timeline");
        }
        public IActionResult AcceptAtList(string usn) {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            friendDAO.AcceptRequest(HttpContext.Session.GetString("username"), usn);
            NotificationListController.sendNoti("accept", null, null, HttpContext.Session.GetString("username"),usn);
            return Redirect ("/Wall/" + HttpContext.Session.GetString("username") + "/requests");
        }
        public IActionResult UnfriendAtWall(string usn) {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            friendDAO.UnfriendOrRefuse(HttpContext.Session.GetString ("username"), usn);
            return Redirect ("/Wall/" + usn + "/timeline");
        }
        public IActionResult UnfriendAtList(string usn) {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            friendDAO.UnfriendOrRefuse(HttpContext.Session.GetString ("username"), usn);
            return Redirect ("/Wall/" + HttpContext.Session.GetString ("username") + "/friends");
        }
        public IActionResult RefuseAtList(string usn) {
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            friendDAO.UnfriendOrRefuse(HttpContext.Session.GetString ("username"), usn);
            return Redirect ("/Wall/" + HttpContext.Session.GetString ("username") + "/requests");
        }
    }
}

Views/Friend/Index.cshtml
@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_Wall.cshtml";
}

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@model List<Friend>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/main.min.css">
<link rel="stylesheet" href="~/css/style.css">
<link rel="stylesheet" href="~/css/color.css">
<link rel="stylesheet" href="~/css/responsive.css">
<script src="~/js/main.min.js"></script>
<script src="~/js/script.js"></script>


<div class="central-meta">
    <div class="frnds">
        <ul class="nav nav-tabs" style="position: relative;">
            <li class="nav-item">My Friends<span>@Model.Count</span></li>
            <li class="nav-item"><a href='/Wall/@HttpContextAccessor.HttpContext.Session.GetString("username")/requests'>Pending Requests</a></li>
        </ul>
        <ul style="list-style-type: none;">
            <li class="nav-item" style="position: absolute; right: 0" id="searchDir"></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active fade show " id="frends">
                <ul class="nearby-contct" id="people-list">
                    @foreach (var item in Model)
                    {
                        <li>
                            <div class="nearly-pepls">

                                @if (item.FirstUsername == HttpContextAccessor.HttpContext.Session.GetString("username"))
                                {
                                    <figure>
                                        <a href="/Wall/@item.SecondUsernameNavigation.Username/timeline" title=""><img src="@item.SecondUsernameNavigation.AvatarSrc" alt=""></a>
                                    </figure>
                                    <div class="pepl-info">
                                        <h4><a href="/Wall/@item.FirstUsernameNavigation.Username/timeline" title="">@item.SecondUsernameNavigation.Nickname</a></h4>
                                        <a href="" onclick='window.location = "@Url.Action("UnfriendAtList","Friend", new {usn = item.SecondUsernameNavigation.Username})";' title="" class="add-butn more-action" style="top: 0;" data-ripple="">unfriend</a>
                                    </div>
                                } else {
                                    <figure>
                                        <a href="/Wall/@item.FirstUsernameNavigation.Username/timeline" title=""><img src="@item.FirstUsernameNavigation.AvatarSrc" alt=""></a>
                                    </figure>
                                    <div class="pepl-info">
                                        <h4><a href="/Wall/@item.FirstUsernameNavigation.Username/timeline" title="">@item.FirstUsernameNavigation.Nickname</a></h4>
                                        <a href="" onclick='window.location = "@Url.Action("UnfriendAtList","Friend", new {usn = item.FirstUsernameNavigation.Username})";' class="add-butn more-action" style="top: 0;" data-ripple="">unfriend</a>
                                    </div>
                                }
                            </div>
                        </li>
                    }


                </ul>
            </div>
        </div>
    </div>

</div>

Views/Friend/RequestList.cshtml
@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_Wall.cshtml";
}

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@model List<Friend>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/main.min.css">
<link rel="stylesheet" href="~/css/style.css">
<link rel="stylesheet" href="~/css/color.css">
<link rel="stylesheet" href="~/css/responsive.css">
<script src="~/js/main.min.js"></script>
<script src="~/js/script.js"></script>


<div class="central-meta">
    <div class="frnds">                                                         
        <ul class="nav nav-tabs">
            <li class="nav-item"><a href='/Wall/@HttpContextAccessor.HttpContext.Session.GetString("username")/friends'>My Friends</a></li>
            <li class="nav-item">Pending Requests<span>@Model.Count</span></li>
        </ul>
        <ul style="list-style-type: none;">
            <li class="nav-item" style="position: absolute; right: 0" id="searchDir"></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active fade show " id="frends">
                <ul class="nearby-contct" id="people-list">
                    @foreach (var item in Model)
                    {
                        <li>
                            <div class="nearly-pepls">

                                @if (item.FirstUsername == HttpContextAccessor.HttpContext.Session.GetString("username"))
                                {
                                    <figure>
                                        <a href="/Wall/@item.SecondUsernameNavigation.Username/timeline" title=""><img src="@item.SecondUsernameNavigation.AvatarSrc" alt=""></a>
                                    </figure>
                                    <div class="pepl-info">
                                        <h4><a href="/Wall/@item.FirstUsernameNavigation.Username/timeline" title="">@item.SecondUsernameNavigation.Nickname</a></h4>
                                        <span style="color: #757575;">@item.StatusTime</span>
                                        <a href="" onclick='window.location = "@Url.Action("AcceptAtList","Friend", new {usn = item.SecondUsernameNavigation.Username})";' title="" class="add-butn more-action" style="top: 0; right: 35%" data-ripple="">Accept</a>
                                        <a href="" onclick='window.location = "@Url.Action("RefuseAtList","Friend", new {usn = item.SecondUsernameNavigation.Username})";' title="" class="add-butn more-action" style="top: 0; right: 10%" data-ripple="">Refuse</a>
                                    </div>
                                } else {
                                    <figure>
                                        <a href="/Wall/@item.FirstUsernameNavigation.Username/timeline" title=""><img src="@item.FirstUsernameNavigation.AvatarSrc" alt=""></a>
                                    </figure>
                                    <div class="pepl-info">
                                        <h4><a href="/Wall/@item.FirstUsernameNavigation.Username/timeline" title="">@item.FirstUsernameNavigation.Nickname</a></h4>
                                        <span style="color: #757575;">@item.StatusTime</span>
                                        <a href="" onclick='window.location = "@Url.Action("AcceptAtList","Friend", new {usn = item.FirstUsernameNavigation.Username})";' class="add-butn more-action" style="top: 0; right: 35%" data-ripple="">Accept</a>
                                        <a href="" onclick='window.location = "@Url.Action("RefuseAtList","Friend", new {usn = item.FirstUsernameNavigation.Username})";' class="add-butn more-action" style="top: 0; right: 10%" data-ripple="">Refuse</a>
                                    </div>
                                }
                            </div>
                        </li>
                    }


                </ul>
            </div>
        </div>
    </div>

</div>

Views/Friend/_FriendStatus.cshtml
@model Friend

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    if (Model.FirstUsername == "")
    {
        <a onclick='window.location = "@Url.Action("AddFriend","Friend", new {usn = Model.SecondUsername })";' title="" id="friend-status" data-ripple="">Add Friend</a>
    }
    else
    {
        if (Model.FriendStatus == 0)
        { 
            if (Model.FirstUsername == HttpContextAccessor.HttpContext.Session.GetString("username")){
                 <a onclick='window.location = "@Url.Action("AddFriend","Friend", new {usn = Model.SecondUsername })";' title="" id="friend-status" data-ripple="">Add Friend</a>
            } else {
                <a onclick='window.location = "@Url.Action("AddFriend","Friend", new {usn = Model.FirstUsername })";' title="" id="friend-status" data-ripple="">Add Friend</a>
            }
        }
        else if (Model.FriendStatus == 1)
        {
            if (HttpContextAccessor.HttpContext.Session.GetString("username") == Model.FirstUsername)
            {
                <a onclick='window.location = "@Url.Action("UnfriendAtWall","Friend", new {usn = Model.SecondUsername })";' title="" id="friend-status"
    data-ripple="">Request Pending</a>
            }
            else
            {
                <a onclick='window.location = "@Url.Action("AcceptAtWall","Friend", new {usn = Model.FirstUsername })";' title="" id="friend-status"
    data-ripple="">Accept Request</a>
            }
        }
        else if (Model.FriendStatus == 2)
        {
            if (HttpContextAccessor.HttpContext.Session.GetString("username") == Model.FirstUsername)
            {
                <a onclick='window.location = "@Url.Action("AcceptAtWall","Friend", new {usn = Model.SecondUsername })";' title="" id="friend-status"
    data-ripple="">Accept Request</a>
            }
            else
            {
                <a onclick='window.location = "@Url.Action("UnfriendAtWall","Friend", new {usn = Model.FirstUsername })";' title="" id="friend-status"
    data-ripple="">Request Pending</a>
            }
        }
        else
        {
            if (Model.FirstUsername == HttpContextAccessor.HttpContext.Session.GetString("username")){
                 <a onclick='window.location = "@Url.Action("UnfriendAtWall","Friend", new {usn = Model.SecondUsername })";' title="" id="friend-status" data-ripple="">Unfriend</a>
            } else {
                <a onclick='window.location = "@Url.Action("UnfriendAtWall","Friend", new {usn = Model.FirstUsername })";' title="" id="friend-status" data-ripple="">Unfriend</a>
            }
        }
    }
}