Models/HobbyList.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace WetCat.Models
{
    public partial class HobbyList
    {
        public int HobbyId { get; set; }
        public string Username { get; set; }
        public int? IsDeleted { get; set; }

        public virtual Hobby Hobby { get; set; }
        public virtual User UsernameNavigation { get; set; }
    }
}

Controllers/HobbyListController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using WetCat.Models;
using WetCat.DAO;
using System.Dynamic;

namespace WetCat.Controllers
{
    public class HobbyListController: Controller
    {
        HobbyListDAO hobbyListDAO = new HobbyListDAO();
        public HobbyListController(){}

        public IActionResult HobbyList(string id){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            HobbyDAO hobbyDAO = new HobbyDAO();
            List<HobbyList> hobbyLists = new List<HobbyList>();
            List<Hobby> hobbies = new List<Hobby>();
            hobbies = hobbyDAO.GetAllHobby();
            hobbyLists = hobbyListDAO.GetHobbyList(id);
            dynamic model = new ExpandoObject();
            List<Hobby> exceptList = new List<Hobby>();
            foreach(HobbyList hl in hobbyLists){
                exceptList.Add(hobbyDAO.GetHobbyByID(hl.HobbyId));
            }            
            for(int i = 0; i < hobbies.Count; ++i){
                for(int j = 0; j < exceptList.Count; ++j){
                    if(hobbies[i].HobbyId == exceptList[j].HobbyId){
                        hobbies.Remove(hobbies[i]);
                        i -= 1;
                        break;
                    }
                }
            }    
            model.HobbyItems = hobbies.Except(exceptList);  
            model.HobbyList = hobbyLists;
            model.User = id;
            return View(model);
        }
        [HttpPost]
        public IActionResult AddHobby(string hb){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            System.Console.WriteLine("HObby " + Convert.ToInt32(hb));
            hobbyListDAO.AddHobby(HttpContext.Session.GetString("username"), Convert.ToInt32(hb));
            return Redirect("/Wall/" + HttpContext.Session.GetString("username") + "/hobby");
        }
        public IActionResult RemoveHobby(string id){
            hobbyListDAO.RemoveHobby(HttpContext.Session.GetString("username"), Convert.ToInt32(id));
            return Redirect("/Wall/" + HttpContext.Session.GetString("username") + "/hobby");
        }
        /*[HttpPost]
        public IActionResult Delete(){
            var Follows = DB.Follows.ToList();
            return View(Follows);
        }*/

    }
}

Views/HobbyList/HobbyList.cshtml
@model dynamic

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
  ViewData["Title"] = "Index";
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/main.min.css">
<link rel="stylesheet" href="~/css/style.css">
<link rel="stylesheet" href="~/css/color.css">
<link rel="stylesheet" href="~/css/responsive.css">
<script src="~/js/main.min.js"></script>
<script src="~/js/script.js"></script>



<div class="central-meta">
  <div class="editing-interest">
    <h5 class="f-title"><i class="ti-heart"></i>@Model.User interests</h5>
    
      <form method="Post" asp-action="AddHobby" asp-controller="HobbyList">
        @if (HttpContextAccessor.HttpContext.Session.GetString("username") == @Model.User)
        {
          <label>Add interests: </label>
          <label for="hb">Choose a new Hobby to Add:</label>
          <select id="hb" name="hb">
            @foreach (Hobby h in Model.HobbyItems)
            {
              <option value="@h.HobbyId">@h.HobbyName</option>
            }
          </select>

          <div class="submit-btns">
            <input type="submit" value="Add" style="float: inline-end">
          </div>
        }
        <ol class="interest-added">
          @foreach (HobbyList i in Model.HobbyList)
          {
            <li>
            <a href="#" title="">
              @i.Hobby.HobbyName
            </a>
            @if (HttpContextAccessor.HttpContext.Session.GetString("username") == @Model.User){
              <span onclick='window.location = "@Url.Action("RemoveHobby","HobbyList", new {id = i.HobbyId })";' class="remove" title="remove">
              <i class="fa fa-close"></i></span>
            }
            </li>

          }
      </ol>
      </form>
      
      
</div>
  </div>


<!--

<div class="row">
@foreach (HobbyList i in Model.HobbyList)
{
      <ol class="col-sm-3 boxContainer interest-added">
          <li><a href="#" title="">@i.Hobby.HobbyName</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
      </ol>
}
</div>-->