Controllers/FollowController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.Models;
using WetCat.DAO;

namespace WetCat.Controllers
{
    public class FollowController: Controller
    {
        FollowDAO followDAO = new FollowDAO();
        public FollowController(){}
/*
        [HttpPost]
        public IActionResult Delete(){
            var Follows = DB.Follows.ToList();
            return View(Follows);
        }
*/
        public IActionResult Follow(string usn){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            Follow fl = new Follow();
            fl.FollowerUsername = HttpContext.Session.GetString("username");
            System.Console.WriteLine("DUoc Follow" + usn);
            fl.FollowedUsername = usn;
            followDAO.Follow(fl);
            return Redirect("/Wall/" + usn + "/timeline");
        }
        public IActionResult Followers(string usn){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            List<Follow> followers = followDAO.GetFollowers(HttpContext.Session.GetString("username")).ToList();
            System.Console.WriteLine("Tui la Followers" + followers.Count);
            return View(followers);
        }

        public IActionResult Followings(string usn){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            List<Follow> followings = followDAO.GetFollowings(HttpContext.Session.GetString("username")).ToList();
            return View(followings);
        }
        public IActionResult UnfollowAtList(string usn){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            System.Console.WriteLine("Unfollow " + usn);
            followDAO.Unfollow(HttpContext.Session.GetString("username"), usn);
            return Redirect("/Wall/" + HttpContext.Session.GetString("username") + "/followings");
        }
        public IActionResult UnfollowAtWall(string usn){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            System.Console.WriteLine("Unfollow " + usn);
            followDAO.Unfollow(HttpContext.Session.GetString("username"), usn);
            return Redirect("/Wall/" + usn + "/timeline");
        }
        public IActionResult FollowStatus(string id){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            System.Console.WriteLine("ID Follow: " + id);
            Follow fl = followDAO.GetFollowStatus(HttpContext.Session.GetString("username"), id);
            if (fl == null){
                fl = new Follow();
                fl.FollowedUsername = id;
                fl.FollowerUsername = "";
            }
            return PartialView("/Views/Follow/_FollowStatus.cshtml", fl);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.DAO;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting;
using WetCat.Models;
using System.Dynamic;

namespace WetCat.Controllers
{
    public class HomeController : Controller
    { 
        UserDAO userDAO = null;
        PostDAO postDAO = null;
        FollowDAO followDAO = null;
        FriendDAO friendDAO = null;
        public HomeController() {
            userDAO = new UserDAO();
            postDAO = new PostDAO();
            followDAO = new FollowDAO();
            friendDAO = new FriendDAO();
        }
        public IActionResult Index(User user)
        {
            if(TempData.ContainsKey("LoginFailed"))
                ViewBag.LoginFailed = TempData["LoginFailed"];
            if (TempData.ContainsKey("UserExisted"))
                ViewBag.UserExisted = TempData["UserExisted"];
            if (TempData.ContainsKey("ConfirmPasswordIncorrect"))
                ViewBag.ConfirmPasswordIncorrect = TempData["ConfirmPasswordIncorrect"];
            if (HttpContext.Session.GetString("username") != null) {
                if (HttpContext.Session.GetString("username") != "admin") return RedirectToAction("Index", "Post");
                return RedirectToAction("Index","Admin");
            }
                
            dynamic model = new ExpandoObject();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string username, string password)
        {
            try {
                if (ModelState.IsValid) {
                    System.Console.WriteLine("HI");
                    User user = userDAO.LoginByUsernameAndPassword(username, password);
                    if (user != null) {
                        HttpContext.Session.SetString("username", user.Username);  
                        if (user.Role == "Admin") 
                            return RedirectToAction("Index", "Admin"); 
                        return RedirectToAction("Index", "Post");
                    } else {
                        
                    }
                        
                }
            } catch (Exception) {

            }
            System.Console.WriteLine("Login failed");
            TempData["LoginFailed"] = "Username or Password incorrect!";
            return RedirectToAction("Index", "Home");
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(User user, string confirmPassword, string Gender) {
            //System.Console.WriteLine(user.Username + " " + user.Password + " " + confirmPassword + " " + user.Gender);
            if (user.Password != confirmPassword) {
                TempData["ConfirmPasswordIncorrect"] = "Confirm Password is incorrect!";
                System.Console.WriteLine("Confirm password is wrong");
                return RedirectToAction("Index", "Home", user);
            }
            User _user = userDAO.GetUserByUsername(user.Username);
            if (_user != null) {
                TempData["UserExisted"] = "Username already existed";
                System.Console.WriteLine("User already existed");
                return RedirectToAction("Index", "Home", user);
            }
            user.Gender = (Gender == "Male") ? 1 : 0;
            user.AvatarSrc = "images/user.jpg";
            userDAO.RegisterUser(user);
            System.Console.WriteLine("Login successfully");
            return RedirectToAction("Index", "Home");
        }

        [HttpGet("/Wall/{usn}/{what}")]
        public IActionResult Wall(string usn, string what){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            System.Console.WriteLine("Xin chao? " + usn);
            //if (what == "") what = "timeline";
            dynamic model = new ExpandoObject();
            User user = userDAO.GetUserByUsername(usn);
            User currentSessionUser = userDAO.GetUserByUsername(HttpContext.Session.GetString("username"));
            ViewBag.AvatarSrc = currentSessionUser.AvatarSrc;
            ViewBag.Username = currentSessionUser.Username;
            return View("/Views/Home/_Wall.cshtml", user);
        }

        public IActionResult Timeline(string id){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            User currentSessionUser = userDAO.GetUserByUsername (HttpContext.Session.GetString ("username"));

            System.Console.WriteLine("timeline " + id);
            PostDAO postDAO = new PostDAO();
            IEnumerable<Post> tempPosts = null;

            IEnumerable<Follow> followings = followDAO.GetFollowings (currentSessionUser.Username);
            IEnumerable<Friend> friends = friendDAO.GetFriendList (currentSessionUser.Username);
            friends = friendDAO.SwapColumnFriend (currentSessionUser.Username, friends);
            IEnumerable<Post> posts = postDAO.GetAllPosts ().ToList ();
            IEnumerable<Post> posts_admin;
            IEnumerable<Post> posts_privacy;
            IEnumerable<Post> posts_following;
            IEnumerable<Post> posts_friend;

            posts = postDAO.GetAllPostsByDeleteStatus (posts);
            posts_admin = postDAO.GetAllAdminPosts (posts);
            tempPosts = posts_admin;
            if (posts_admin != null) {
                tempPosts = tempPosts.Union (posts_admin.ToHashSet ());
            }

            posts_privacy = postDAO.GetAllPostsByPrivacy (currentSessionUser.Username, posts);
            if (posts_privacy != null) {
                tempPosts = tempPosts.Union (posts_privacy.ToHashSet ());
            }

            foreach (Follow following in followings) {
                posts_following = postDAO.GetAllPostsByFollowings (currentSessionUser.Username, posts, following);
                if (posts_following != null)
                    tempPosts = tempPosts.Union (posts_following.ToHashSet ());
            }

            foreach (Friend friend in friends) {
                posts_friend = postDAO.GetAllPostsByFriends (currentSessionUser.Username, posts, friend);
                if (posts_friend != null) {
                    tempPosts = tempPosts.Union (posts_friend.ToHashSet ());
                }
            }
            dynamic model = new ExpandoObject();
            posts = tempPosts.ToList().FindAll(p => p.PostAuthor == id);
            model.postsList = posts;
            model.currentSessionUser = userDAO.GetUserByUsername(HttpContext.Session.GetString("username"));
            return View("/Views/Home/Timeline.cshtml", model);
        }

        public IActionResult Follow(string id){
            List<Follow> Followings = followDAO.GetFollowings(id);
            return View("/Views/Follow/Followings.cshtml",Followings);
        }

        [HttpPost]
        public IActionResult Search(string data){
            if (HttpContext.Session.GetString ("username") == null) {
                return RedirectToAction ("Index", "Home");
            }
            if (data == "") return View(data);
            
            data = data.ToLower();
            System.Console.WriteLine("DATA " + data);
            List<User> result = userDAO.GetUsers().ToList()
            .Where(p =>    p.Nickname.ToString().ToLower().Contains(data)
                        || p.UserMail.ToString().ToLower() == data).ToList();
            return View(result);
        }

        public IActionResult Logout()
        {
            System.Console.WriteLine("Im going to logout");
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        
    }
}

Controllers/ReactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.Models;
using System.Dynamic;
using WetCat.DAO;

namespace WetCat.Controllers
{
    public class ReactController: Controller
    {
        ReactDAO reactDAO = new ReactDAO();
        public ReactController(){}
        
        public IActionResult GetReactStatus(string id){
            ReactList rl = reactDAO.GetReactStatus(Convert.ToInt32(id), HttpContext.Session.GetString("username"));
            if(rl == null){ 
                rl = new ReactList();
                rl.PostId = Convert.ToInt32(id);
                rl.ReactType = "";
            }
            System.Console.WriteLine("DAY LA REACT STATUS " + id);
            return PartialView("/Views/React/_ReactStatus.cshtml", rl);
        }

        public IActionResult SetReact(string id, string type){
            if (type == "delete"){
                reactDAO.Unreact(Convert.ToInt32(id), HttpContext.Session.GetString("username"));
            } else {
                type = type.Substring(0, type.Length - "-icon".Length);
                System.Console.WriteLine("SET " + id + type);
                reactDAO.ReactPost(Convert.ToInt32(id), HttpContext.Session.GetString("username"), type);
                PostDAO pD = new PostDAO();
                NotificationListController.sendNoti("react", Convert.ToInt32(id), null, HttpContext.Session.GetString("username"), pD.GetPost(Convert.ToInt32(id)).PostAuthor);
            }
                return GetReactStatus(id);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WetCat.DAO;
using WetCat.Models;

namespace WetCat.Controllers
{
    public class UserController : Controller
    {
        UserDAO userDAO = null;
        public UserController() {
            userDAO = new UserDAO();
        }
        public IActionResult Index()
        {
            string usn = HttpContext.Session.GetString("username");
            User user = userDAO.GetUserByUsername(usn);
            return View(user);
        }
        
        public IActionResult Edit()
        {
            string username = HttpContext.Session.GetString("username");
            User user = userDAO.GetUserByUsername(username);
            //System.Console.WriteLine("Hi");
            return View(user);
        }

        [HttpPost]
        public IActionResult Edit(User user, string gender)
        {
            user.Gender = (gender == "Male") ? 1 : 0;
            userDAO.EditUser(user);
            return Redirect ("/Wall/" + user.Username + "/timeline");
        }

        [HttpPost]
        public IActionResult UploadAvatar(string file)
        {
            System.Console.WriteLine("Im in upload avatar!");
            string author = HttpContext.Session.GetString("username");  
            byte[] bytes = Convert.FromBase64String(file.Split(',')[1]);
            string dirPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/profiles/" + author);
            if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);
            System.Console.WriteLine("Created dir path!");
            string fileName = Guid.NewGuid() + ".png";
            var filePath = Path.Combine(dirPath, fileName);
            using var fileStream = new FileStream(filePath, FileMode.Create);
            fileStream.Write(bytes, 0, bytes.Length);
            fileStream.Flush();
            string imgSrc = String.Format("images/profiles/{0}/{1}", author, fileName);
            userDAO.UpdateAvatar(author,imgSrc);
            System.Console.WriteLine(userDAO.GetUserByUsername(author).AvatarSrc);
            return Redirect ("/Wall/" + author + "/timeline");
        }
        
        [HttpPost]
        public IActionResult UploadWallpaper(IFormFile file)  
        {  
            System.Console.WriteLine("Im in upload wallpaper");
            string imgSrc = null;  
            string author = HttpContext.Session.GetString("username");   
            if (file != null)  
            {  
                string dirPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/profiles/" + author);

                if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);

                var filePath = Path.Combine(dirPath, file.FileName);

                using var fileStream = new FileStream(filePath, FileMode.Create);
                file.CopyTo(fileStream);

                imgSrc = String.Format("images/profiles/{0}/{1}", author, file.FileName);
                userDAO.UpdateWallpaper(author,imgSrc);
            }  
            return Redirect ("/Wall/" + author + "/timeline");      
        }
    }
}

Views/Home/_Wall.cshtml
@model User

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">


<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<title>WetCat Social Network</title>
	<link rel="icon" href="~/~/images/fav.png" type="image/png" sizes="16x16">
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<link rel="stylesheet" href="~/css/main.min.css">
	<link rel="stylesheet" href="~/css/style.css">
	<link rel="stylesheet" href="~/css/color.css">
	<link rel="stylesheet" href="~/css/responsive.css">
	<link rel="stylesheet" href="~/css/pixelarity.css">
	<script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
	<script src="~/js/main.min.js"></script>
	<script src="~/js/script.js"></script>

</head>

<body>
		<div class="topbar stick">
			<div class="logo">
				<a title="" href="#"><img class="" id="web_logo" src="images/profiles/admin/logo.jpg" alt=""></a>
			</div>
			<div class="top-area">
				<div class="top-search">
					<form method="post" asp-action="Search" asp-controller="Home">
						<input type="text" placeholder="Search Friend" required="required" name="data">
						<button data-ripple><i class="ti-search"></i></button>
					</form>
				</div>
				<div class="user-img">
					<img src="~/@ViewBag.AvatarSrc" style="max-width: 50px">
					<span class="status f-online"></span>
					<div class="user-setting">		
						<a href="/Wall/@ViewBag.Username/edit" title=""><i class="ti-pencil-alt"></i>edit profile</a>
						<a asp-action="Logout" asp-controller="Home" title=""><i class="ti-power-off"></i>log out</a>			
					</div>
				</div>
			</div>
		</div><!-- topbar -->

		<section>
			<div class="feature-photo">
					@if (Model == null || Model.BackgroundSrc == null)
					{
						<figure style="width: auto;">
							<img src="~/images/resources/timeline-1.jpg" alt="">
						</figure>
					}
					else
					{
						<figure>
							<img src="~/@Model.BackgroundSrc" alt="">
						</figure>
					}	
				<div class="add-btn">
					<span id="followers-count"></span>
					@if (Model.Username != HttpContextAccessor.HttpContext.Session.GetString("username"))
					{
						<a href="#" title="" id="follow-status" data-ripple=""></a>
						<a href="#" title="" id="friend-status" data-ripple="">Add Friend</a>
						<script>
							$(window).on("load", function () {
								var id = "@Model.Username";
								$.ajax({
									url: "@Url.Action("FriendStatus", "Friend")",
									data: { id: id },
									success: function (jsReturnArgs) {
										$("#friend-status").html(jsReturnArgs);
									}
								});
								$.ajax({
									url: "@Url.Action("FollowStatus", "Follow")",
									data: { id: id },
									success: function (jsReturnArgs) {
										$("#follow-status").html(jsReturnArgs);
									}
								});
							});
						</script>
					}

				</div>
				@if (Model.Username == HttpContextAccessor.HttpContext.Session.GetString("username")) {
					<form id="wallpaperForm" class="edit-phto" asp-action="UploadWallpaper" asp-controller="User"
						enctype="multipart/form-data">
						<i class="fa fa-camera-retro"></i>
						<label class="fileContainer">
							Edit Cover Photo
							<input type="file" name="file" id="wallpaper">
						</label>
					</form>
				}
				<div class="container-fluid">
					<div class="row merged">
						<div class="col-lg-2 col-sm-3">
							<div class="user-avatar">
								<figure>
									@if (Model == null || Model.AvatarSrc == null)
									{
										<img id="result" src="~/images/resources/user-avatar.jpg" alt="">
									}
									else
									{
										<img id="result" src="~/@Model.AvatarSrc" alt="">
									}
									@if (Model.Username == HttpContextAccessor.HttpContext.Session.GetString("username")) {
										<form method="POST" id="avatarForm" class="edit-phto" asp-action="UploadAvatar"
											asp-controller="User" enctype="multipart/form-data">
											<i class="fa fa-camera-retro"></i>
											<label class="fileContainer">
												Edit Display Photo
												<input type="text" name="file" id="imgbase64" hidden />
												<input id="file" type="file" />
											</label>
										</form>
									}
								</figure>
							</div>
						</div>
						<div class="col-lg-10 col-sm-9">
							<div class="timeline-info">
								<ul>
									<li class="admin-name">
										<h5>@Model.Nickname</h5>
									</li>
									<li>
										<a class="" id="timeline" href="timeline" title="" data-ripple="">time
											line</a>
										@{
											if (Model.Username ==
			HttpContextAccessor.HttpContext.Session.GetString("username"))
											{
												<a class="" id="edit" href="edit" title="" data-ripple="">Edit</a>
												<a class="" href="friends" title="" data-ripple="">Friends</a>
												<a class="" href="followers" title="" data-ripple="">Followers</a>
												<a class="" href="followings" title="" data-ripple="">Followings</a>
											}
										}

										<a class="" id="more" href="hobby" title="" data-ripple="">Hobby</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- top area -->

		<section>
			<div class="gap gray-bg">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<div class="row" id="page-contents">
								<div class="col-lg-3">
									<aside class="sidebar static">


										<div class="widget">
											<h4 class="widget-title">Shortcuts</h4>
											<ul class="naves">
												<li>
													<i class="ti-clipboard"></i>
													<a asp-action="Index" asp-controller="Post">News feed</a>
												</li>
												<li>
													<i class="ti-files"></i>
													<a href="/Wall/@ViewBag.Username/timeline">My pages</a>
												</li>
												<li>
													<i class="ti-user"></i>
													<a href="/Wall/@ViewBag.Username/friends">friends</a>
												</li>
												<li>
													<i class="ti-power-off"></i>
													<a asp-action="Logout" asp-controller="Home" title="">Logout</a>
												</li>
											</ul>
										</div><!-- Shortcuts -->
									</aside>
								</div><!-- sidebar -->
								<div class="col-lg-6">
									<div id="mainrender">

									</div>
									@{
										if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "timeline")
										{
											<script>
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("Timeline", "Home")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
										else if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "photos")
										{
											<script>
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("Follow", "Home")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
										else if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "hobby")
										{
											<script>
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("HobbyList", "HobbyList")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
										else if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "requests")
										{
											<script>
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("RequestList", "Friend")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
										else if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "friends")
										{
											<script>
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("Index", "Friend")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
										else if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "followings")
										{
											<script>
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("Followings", "Follow")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
										else if
											(this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/" + Model.Username + "/") +
											Model.Username.Length + 2) == "followers")
										{
											<script>

												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("Followers", "Follow")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}	
										else if (this.Url.PageLink().Substring(this.Url.PageLink().IndexOf("/"+Model.Username+"/") + Model.Username.Length+2) == "edit"){
											<script>
												
												$(window).on("load", function () {
													var id = "@Model.Username";
													$.ajax({
														url: "@Url.Action("Edit", "User")",
														data: { id: id },
														success: function (jsReturnArgs) {
															$("#mainrender").html(jsReturnArgs);
														}
													});
												});
											</script>
										}
									}

								</div><!-- centerl meta -->
								<div class="col-lg-3">
									<aside class="sidebar static">

										<div class="widget friend-list stick-widget">
											<h4 class="widget-title">Quotes</h4>
											<ul class="friendz-list">
												@Model.Quote
											</ul>
										</div><!-- friends list sidebar -->
									</aside>
								</div><!-- sidebar -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>


		<div class="bottombar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
					</div>
				</div>
			</div>
		</div>
	</div>
	<script src="~/js/pixelarity.js"></script>
	<script>
		$(document).ready(function () {
			$("#file").change(function (e) {
				var img = e.target.files[0];
				if (!pixelarity.open(img, true, function (res) {
					$("#result").attr("src", res);
					document.getElementById("imgbase64").value = res;
					$("#avatarForm").submit();
					//alert(document.getElementById("imgbase64").value);
				}, "jpg", 1)) {
					alert("Whoops! That is not an image!");
				}
			});
			$("#wallpaper").change(function (e) {
				$("#wallpaperForm").submit();
			});
		});
	</script>
</body>

</html>